channels:
- http://ssb.stsci.edu/astroconda
- conda-forge
- defaults
dependencies:
- pip
- python==3.8.5
- pip:
    - ipython==7.20.0
    - jupyter==1.0.0
    - matplotlib==3.3.4
    - numpy==1.20.1
    - pandas==1.3.2
    - pysiaf==0.11.0
    - pytest==6.2.2
    - sphinx==3.5.1